In [1]:
import pandas as pd
import numpy as np
import pickle

# Preprocess Steps

In [2]:
#Set parameters to see all data
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 1000)

In [3]:
# Load Train dataset
test_1 = pd.read_csv("../data/SurusTesti1.csv", delimiter = ";")
test_2 = pd.read_csv("../data/SurusTesti2.csv", delimiter = ";")

In [4]:
# Load cycle_df dataset
cycle_df = pd.read_csv("../data/cycle_df_for_main_cycles.csv")
cycle_df.head(5).append(cycle_df.tail(5))

      TotalTime             Phase  PhaseTime        Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count
0           236  artemis_motor130         60  30.333333  0.694444        30.68981         0.03194         30.68981          0.03194         30.68981          0.03194         30.68981          0.03194        -0.27778         0.69444        -0.27778         0.69444                     0.0
1           237  artemis_motor130         61  31.027778  0.416667        30.69536         0.03825         30.69536          0.03825         30.69536          0.03825         30.69536          0.03825        -0.27778         0.69444        -0.27778         0.69444                     0.0
2           238  artemis_motor130         62  31.444444  0.666667        30.70744         0.04839         30.70744          0.04839         30.70744          0.04839         30.70744          0.04839        -0.27778         0.69444        -0.27778         0.69444                     0.0
3           239  artemis_motor130         63  32.111111  0.555556        30.72972         0.05644         30.72972          0.05644         30.72972          0.05644         30.72972          0.05644        -0.27778         0.69444        -0.27778         0.69444                     0.0
4           240  artemis_motor130         64  32.666667  0.694444        30.75998         0.06641         30.75998          0.06641         30.75998          0.06641         30.75998          0.06641        -0.27778         0.69444        -0.27778         0.69444                     0.0
8075       8881      wltp_class3b        319   0.000000  0.000000        12.94729         0.00000         12.94729          0.00000         12.94729          0.00000         12.94729          0.00000        -1.50000         1.66667        -1.50000         1.66667                     2.0
8076       8882      wltp_class3b        320   0.000000  0.000000        12.94009         0.00000         12.94009          0.00000         12.94009          0.00000         12.94009          0.00000        -1.50000         1.66667        -1.50000         1.66667                     3.0
8077       8883      wltp_class3b        321   0.000000  0.000000        12.93289         0.00000         12.93289          0.00000         12.93289          0.00000         12.93289          0.00000        -1.50000         1.66667        -1.50000         1.66667                     4.0
8078       8884      wltp_class3b        322   0.000000  0.000000        12.92571         0.00000         12.92571          0.00000         12.92571          0.00000         12.92571          0.00000        -1.50000         1.66667        -1.50000         1.66667                     5.0
8079       8885      wltp_class3b        323   0.000000  0.000000        12.91853         0.00000         12.91853          0.00000         12.91853          0.00000         12.91853          0.00000        -1.50000         1.66667        -1.50000         1.66667                     6.0

In [5]:
test_1.head(5).append(test_1.tail(5))

      TotalTime   Phase  PhaseTime       Vel       Acc
0             1  Drive1          1  0.086806  0.000000
1             2  Drive1          2  0.086806 -0.086806
2             3  Drive1          3  0.000000  0.000000
3             4  Drive1          4  0.000000  0.000000
4             5  Drive1          5  0.000000  0.000000
1100       1101  Drive1       1101  0.000000  0.000000
1101       1102  Drive1       1102  0.000000  0.000000
1102       1103  Drive1       1103  0.000000  0.000000
1103       1104  Drive1       1104  0.000000  0.000000
1104       1105  Drive1       1105  0.000000  0.000000

In [6]:
test_2.head(5).append(test_2.tail(5))

      TotalTime   Phase  PhaseTime  Vel  Acc
0             1  Drive2          1  0.0  0.0
1             2  Drive2          2  0.0  0.0
2             3  Drive2          3  0.0  0.0
3             4  Drive2          4  0.0  0.0
4             5  Drive2          5  0.0  0.0
1822       1823  Drive2       1823  0.0  0.0
1823       1824  Drive2       1824  0.0  0.0
1824       1825  Drive2       1825  0.0  0.0
1825       1826  Drive2       1826  0.0  0.0
1826       1827  Drive2       1827  0.0  0.0

In [7]:
test_1.shape, test_2.shape, cycle_df.shape

((1105, 5), (1827, 5), (8080, 18))

In [8]:
test_1 = test_1.drop({'Phase', 'TotalTime'}, axis=1)

In [9]:
test_2 = test_2.drop({'Phase', 'TotalTime'}, axis=1)

In [10]:
period = [5, 10, 30, 60]
process = ['Vel', 'Acc']

In [11]:
for per in period:
    for pro in process:
        col = str(per) + "_sec_" + str(pro)+ "_mean"
        test_1[col] = test_1[pro].expanding(min_periods=per).mean().round(5)
        test_2[col] = test_2[pro].expanding(min_periods=per).mean().round(5)
        cycle_df[col] = cycle_df[pro].expanding(min_periods=per).mean().round(5)

In [12]:
period_2 = [30, 60]
process_2 = ['Acc']
for per in period_2:
    for pro in process_2:
        col_min = str(per) + "_sec_" + str(pro)+ "_min"
        col_max = str(per) + "_sec_" + str(pro)+ "_max"

        test_1[col_min] = test_1[process_2].expanding(min_periods=per).min().round(5)
        test_1[col_max] = test_1[process_2].expanding(min_periods=per).max().round(5)

        test_2[col_min] = test_2[process_2].expanding(min_periods=per).min().round(5)
        test_2[col_max] = test_2[process_2].expanding(min_periods=per).max().round(5)
        
        cycle_df[col_min] = cycle_df[process_2].expanding(min_periods=per).min().round(5)
        cycle_df[col_max] = cycle_df[process_2].expanding(min_periods=per).max().round(5)

In [13]:
test_2.head()

   PhaseTime  Vel  Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max
0          1  0.0  0.0             NaN             NaN              NaN              NaN              NaN              NaN              NaN              NaN             NaN             NaN             NaN             NaN
1          2  0.0  0.0             NaN             NaN              NaN              NaN              NaN              NaN              NaN              NaN             NaN             NaN             NaN             NaN
2          3  0.0  0.0             NaN             NaN              NaN              NaN              NaN              NaN              NaN              NaN             NaN             NaN             NaN             NaN
3          4  0.0  0.0             NaN             NaN              NaN              NaN              NaN              NaN              NaN              NaN             NaN             NaN             NaN             NaN
4          5  0.0  0.0             0.0             0.0              NaN              NaN              NaN              NaN              NaN              NaN             NaN             NaN             NaN             NaN

In [14]:
print("*****test_1******")
print(test_1['Vel'].isin([0]).expanding(min_periods=60).sum().max())
print(test_1['Vel'].isin([0]).expanding(min_periods=60).sum().min())

print("*****test_2******")
print(test_2['Vel'].isin([0]).expanding(min_periods=60).sum().max())
print(test_2['Vel'].isin([0]).expanding(min_periods=60).sum().min())

print("*****cycle_df******")
print(cycle_df['Vel'].isin([0]).expanding(min_periods=60).sum().max())
print(cycle_df['Vel'].isin([0]).expanding(min_periods=60).sum().min())

*****test_1******
328.0
38.0
*****test_2******
253.0
18.0
*****cycle_df******
997.0
0.0

In [15]:
# dummy function to count zeros
count_func = lambda x: (x==0).sum()

summed_1 = test_1['Vel'].rolling(50).apply(count_func)
summed_2 = test_2['Vel'].rolling(50).apply(count_func)
summed_cycle = cycle_df['Vel'].rolling(50).apply(count_func)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  """
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning

In [16]:
period_2 = 60
process_2 = 'Vel'

# dummy function to count zeros
count_func = lambda x: (x==0).sum()

iddle_count = str(period_2) + "_sec_" + str(process_2)+ "_iddle_count"
print("******* " + iddle_count + " *******")

test_1[iddle_count] = 0
test_1[iddle_count] = test_1['Vel'].rolling(60).apply(count_func)

test_2[iddle_count] = 0
test_2[iddle_count] = test_2['Vel'].rolling(60).apply(count_func)

cycle_df[iddle_count] = 0
cycle_df[iddle_count] = cycle_df['Vel'].rolling(60).apply(count_func)

******* 60_sec_Vel_iddle_count *******

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  # This is added back by InteractiveShellApp.init_path()
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:14: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:17: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning

In [17]:
test_1 = test_1[59:]

test_2 = test_2[59:]

cycle_df = cycle_df[59:]

# Prediction Steps

In [18]:
phase_mapping = {
    "artemis_motor130" : "10",
    "artemis_road" : "30",
    "artemis_urban" : "50",
    "ftp72" : "70",
    "ftp_us06" : "90",
    "hwfet" : "110",
    "nycc" : "130",
    "rts95" : "150",
    "wltp_class3b" : "170",
}

In [19]:
invertion_phase_mapping = {
    "10" : "artemis_motor130",
    "30" : "artemis_road",
    "50" : "artemis_urban",
    "70" : "ftp72",
    "90" : "ftp_us06",
    "110" : "hwfet",
    "130" : "nycc",
    "150" : "rts95",
    "170" : "wltp_class3b",
}

In [20]:
cycle_df.head()

    TotalTime             Phase  PhaseTime        Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count
59        295  artemis_motor130        119  36.416667 -0.138889        34.40972         0.09907         34.40972          0.09907         34.40972          0.09907         34.40972          0.09907        -0.80556         0.69444        -0.80556         0.69444                     0.0
60        296  artemis_motor130        120  36.277778  0.000000        34.44035         0.09745         34.44035          0.09745         34.44035          0.09745         34.44035          0.09745        -0.80556         0.69444        -0.80556         0.69444                     0.0
61        297  artemis_motor130        121  36.277778 -0.138889        34.46998         0.09364         34.46998          0.09364         34.46998          0.09364         34.46998          0.09364        -0.80556         0.69444        -0.80556         0.69444                     0.0
62        298  artemis_motor130        122  36.138889  0.000000        34.49647         0.09215         34.49647          0.09215         34.49647          0.09215         34.49647          0.09215        -0.80556         0.69444        -0.80556         0.69444                     0.0
63        299  artemis_motor130        123  36.138889 -0.138889        34.52214         0.08854         34.52214          0.08854         34.52214          0.08854         34.52214          0.08854        -0.80556         0.69444        -0.80556         0.69444                     0.0

In [21]:
cycle_df.shape

(8021, 18)

In [22]:
def convert_phase(df, column_name, phase_dict):
    df[column_name] = df[column_name].replace(phase_dict)
    return df

In [23]:
cycle_df = convert_phase(cycle_df, "Phase", phase_mapping)

In [24]:
cycle_df = cycle_df.drop({'TotalTime'}, axis=1)

In [25]:
cycle_df.head()

   Phase  PhaseTime        Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count
59    10        119  36.416667 -0.138889        34.40972         0.09907         34.40972          0.09907         34.40972          0.09907         34.40972          0.09907        -0.80556         0.69444        -0.80556         0.69444                     0.0
60    10        120  36.277778  0.000000        34.44035         0.09745         34.44035          0.09745         34.44035          0.09745         34.44035          0.09745        -0.80556         0.69444        -0.80556         0.69444                     0.0
61    10        121  36.277778 -0.138889        34.46998         0.09364         34.46998          0.09364         34.46998          0.09364         34.46998          0.09364        -0.80556         0.69444        -0.80556         0.69444                     0.0
62    10        122  36.138889  0.000000        34.49647         0.09215         34.49647          0.09215         34.49647          0.09215         34.49647          0.09215        -0.80556         0.69444        -0.80556         0.69444                     0.0
63    10        123  36.138889 -0.138889        34.52214         0.08854         34.52214          0.08854         34.52214          0.08854         34.52214          0.08854        -0.80556         0.69444        -0.80556         0.69444                     0.0

In [26]:
cycle_df.iloc[:,0]

59       10
60       10
61       10
62       10
63       10
       ...
8075    170
8076    170
8077    170
8078    170
8079    170
Name: Phase, Length: 8021, dtype: object

In [27]:
cycle_df.iloc[:,2:17]

            Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count
59    36.416667 -0.138889        34.40972         0.09907         34.40972          0.09907         34.40972          0.09907         34.40972          0.09907        -0.80556         0.69444        -0.80556         0.69444                     0.0
60    36.277778  0.000000        34.44035         0.09745         34.44035          0.09745         34.44035          0.09745         34.44035          0.09745        -0.80556         0.69444        -0.80556         0.69444                     0.0
61    36.277778 -0.138889        34.46998         0.09364         34.46998          0.09364         34.46998          0.09364         34.46998          0.09364        -0.80556         0.69444        -0.80556         0.69444                     0.0
62    36.138889  0.000000        34.49647         0.09215         34.49647          0.09215         34.49647          0.09215         34.49647          0.09215        -0.80556         0.69444        -0.80556         0.69444                     0.0
63    36.138889 -0.138889        34.52214         0.08854         34.52214          0.08854         34.52214          0.08854         34.52214          0.08854        -0.80556         0.69444        -0.80556         0.69444                     0.0
...         ...       ...             ...             ...              ...              ...              ...              ...              ...              ...             ...             ...             ...             ...                     ...
8075   0.000000  0.000000        14.57652        -0.00576         14.57652         -0.00576         14.57652         -0.00576         14.57652         -0.00576        -3.61111         3.08458        -3.61111         3.08458                     2.0
8076   0.000000  0.000000        14.57471        -0.00576         14.57471         -0.00576         14.57471         -0.00576         14.57471         -0.00576        -3.61111         3.08458        -3.61111         3.08458                     3.0
8077   0.000000  0.000000        14.57291        -0.00576         14.57291         -0.00576         14.57291         -0.00576         14.57291         -0.00576        -3.61111         3.08458        -3.61111         3.08458                     4.0
8078   0.000000  0.000000        14.57110        -0.00576         14.57110         -0.00576         14.57110         -0.00576         14.57110         -0.00576        -3.61111         3.08458        -3.61111         3.08458                     5.0
8079   0.000000  0.000000        14.56930        -0.00576         14.56930         -0.00576         14.56930         -0.00576         14.56930         -0.00576        -3.61111         3.08458        -3.61111         3.08458                     6.0

[8021 rows x 15 columns]

In [28]:
X = cycle_df.iloc[:,2:17]
y = cycle_df.iloc[:,0]

In [29]:
X.columns

Index(['Vel', 'Acc', '5_sec_Vel_mean', '5_sec_Acc_mean', '10_sec_Vel_mean', '10_sec_Acc_mean', '30_sec_Vel_mean', '30_sec_Acc_mean', '60_sec_Vel_mean', '60_sec_Acc_mean', '30_sec_Acc_min', '30_sec_Acc_max', '60_sec_Acc_min', '60_sec_Acc_max', '60_sec_Vel_iddle_count'], dtype='object')

In [30]:
test_1.columns

Index(['PhaseTime', 'Vel', 'Acc', '5_sec_Vel_mean', '5_sec_Acc_mean', '10_sec_Vel_mean', '10_sec_Acc_mean', '30_sec_Vel_mean', '30_sec_Acc_mean', '60_sec_Vel_mean', '60_sec_Acc_mean', '30_sec_Acc_min', '30_sec_Acc_max', '60_sec_Acc_min', '60_sec_Acc_max', '60_sec_Vel_iddle_count'], dtype='object')

In [31]:
test_2.columns

Index(['PhaseTime', 'Vel', 'Acc', '5_sec_Vel_mean', '5_sec_Acc_mean', '10_sec_Vel_mean', '10_sec_Acc_mean', '30_sec_Vel_mean', '30_sec_Acc_mean', '60_sec_Vel_mean', '60_sec_Acc_mean', '30_sec_Acc_min', '30_sec_Acc_max', '60_sec_Acc_min', '60_sec_Acc_max', '60_sec_Vel_iddle_count'], dtype='object')

In [32]:
test_1 = test_1.drop({'PhaseTime'}, axis=1)
test_2 = test_2.drop({'PhaseTime'}, axis=1)

In [33]:
# load the model from disk
filename = '../models/KNC_model_for_main_cycles.sav'
loaded_model = pickle.load(open(filename, 'rb'))

In [34]:
best_KNC = loaded_model.fit(X, y)
phase_predictor_1 = best_KNC.predict(test_1)
phase_predictor_2 = best_KNC.predict(test_2)

print(phase_predictor_1)

['170' '170' '170' ... '70' '70' '70']

In [35]:
print(phase_predictor_2)

['70' '70' '70' ... '170' '170' '170']

In [36]:
test_1.head()

          Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count
59  13.107639  0.065312         3.55149         0.21810          3.55149          0.21810          3.55149          0.21810          3.55149          0.21810        -0.19536         2.83086        -0.19536         2.83086                    38.0
60  13.172951 -0.113187         3.70922         0.21267          3.70922          0.21267          3.70922          0.21267          3.70922          0.21267        -0.19536         2.83086        -0.19536         2.83086                    38.0
61  13.059764 -0.073653         3.86004         0.20805          3.86004          0.20805          3.86004          0.20805          3.86004          0.20805        -0.19536         2.83086        -0.19536         2.83086                    38.0
62  12.986111 -0.100919         4.00490         0.20315          4.00490          0.20315          4.00490          0.20315          4.00490          0.20315        -0.19536         2.83086        -0.19536         2.83086                    37.0
63  12.885192 -0.220708         4.14365         0.19653          4.14365          0.19653          4.14365          0.19653          4.14365          0.19653        -0.22071         2.83086        -0.22071         2.83086                    36.0

In [37]:
test_1['phase_prediction'] = phase_predictor_1
test_2['phase_prediction'] = phase_predictor_2

In [38]:
test_1 = convert_phase(test_1, "phase_prediction", invertion_phase_mapping)
test_2 = convert_phase(test_2, "phase_prediction", invertion_phase_mapping)

In [39]:
#Export dataframe as a csv
test_1.to_csv("../data/test_1_result_for_main_cycles.csv", index=0)
test_2.to_csv("../data/test_2_result_for_main_cycles.csv", index=0)

In [40]:
test_1.head(20).append(test_1.tail(20))

            Vel       Acc  5_sec_Vel_mean  5_sec_Acc_mean  10_sec_Vel_mean  10_sec_Acc_mean  30_sec_Vel_mean  30_sec_Acc_mean  60_sec_Vel_mean  60_sec_Acc_mean  30_sec_Acc_min  30_sec_Acc_max  60_sec_Acc_min  60_sec_Acc_max  60_sec_Vel_iddle_count phase_prediction
59    13.107639  0.065312         3.55149         0.21810          3.55149          0.21810          3.55149          0.21810          3.55149          0.21810        -0.19536         2.83086        -0.19536         2.83086                    38.0     wltp_class3b
60    13.172951 -0.113187         3.70922         0.21267          3.70922          0.21267          3.70922          0.21267          3.70922          0.21267        -0.19536         2.83086        -0.19536         2.83086                    38.0     wltp_class3b
61    13.059764 -0.073653         3.86004         0.20805          3.86004          0.20805          3.86004          0.20805          3.86004          0.20805        -0.19536         2.83086        -0.19536         2.83086                    38.0     wltp_class3b
62    12.986111 -0.100919         4.00490         0.20315          4.00490          0.20315          4.00490          0.20315          4.00490          0.20315        -0.19536         2.83086        -0.19536         2.83086                    37.0     wltp_class3b
63    12.885192 -0.220708         4.14365         0.19653          4.14365          0.19653          4.14365          0.19653          4.14365          0.19653        -0.22071         2.83086        -0.22071         2.83086                    36.0     wltp_class3b
64    12.664485 -0.147124         4.27474         0.19124          4.27474          0.19124          4.27474          0.19124          4.27474          0.19124        -0.22071         2.83086        -0.22071         2.83086                    35.0     wltp_class3b
65    12.517361  0.309286         4.39963         0.19303          4.39963          0.19303          4.39963          0.19303          4.39963          0.19303        -0.22071         2.83086        -0.22071         2.83086                    34.0     wltp_class3b
66    12.826647  0.243029         4.52541         0.19377          4.52541          0.19377          4.52541          0.19377          4.52541          0.19377        -0.22071         2.83086        -0.22071         2.83086                    33.0     wltp_class3b
67    13.069676  0.093285         4.65106         0.19230          4.65106          0.19230          4.65106          0.19230          4.65106          0.19230        -0.22071         2.83086        -0.22071         2.83086                    32.0     wltp_class3b
68    13.162961  0.097727         4.77442         0.19093          4.77442          0.19093          4.77442          0.19093          4.77442          0.19093        -0.22071         2.83086        -0.22071         2.83086                    31.0     wltp_class3b
69    13.260688 -0.262153         4.89565         0.18445          4.89565          0.18445          4.89565          0.18445          4.89565          0.18445        -0.26215         2.83086        -0.26215         2.83086                    30.0     wltp_class3b
70    12.998536 -0.781290         5.00978         0.17085          5.00978          0.17085          5.00978          0.17085          5.00978          0.17085        -0.78129         2.83086        -0.78129         2.83086                    29.0     wltp_class3b
71    12.217246 -1.066798         5.10988         0.15366          5.10988          0.15366          5.10988          0.15366          5.10988          0.15366        -1.06680         2.83086        -1.06680         2.83086                    28.0     wltp_class3b
72    11.150448 -1.434598         5.19263         0.13190          5.19263          0.13190          5.19263          0.13190          5.19263          0.13190        -1.43460         2.83086        -1.43460         2.83086                    27.0     wltp_class3b
73     9.715850 -1.694888         5.25375         0.10722          5.25375          0.10722          5.25375          0.10722          5.25375          0.10722        -1.69489         2.83086        -1.69489         2.83086                    26.0            ftp72
74     8.020961 -2.272785         5.29065         0.07548          5.29065          0.07548          5.29065          0.07548          5.29065          0.07548        -2.27279         2.83086        -2.27279         2.83086                    25.0            ftp72
75     5.748176 -3.379077         5.29667         0.03003          5.29667          0.03003          5.29667          0.03003          5.29667          0.03003        -3.37908         2.83086        -3.37908         2.83086                    24.0            ftp72
76     2.369099 -2.118663         5.25865         0.00213          5.25865          0.00213          5.25865          0.00213          5.25865          0.00213        -3.37908         2.83086        -3.37908         2.83086                    23.0            ftp72
77     0.250436 -0.250436         5.19444        -0.00111          5.19444         -0.00111          5.19444         -0.00111          5.19444         -0.00111        -3.37908         2.83086        -3.37908         2.83086                    22.0            ftp72
78     0.000000  0.000000         5.12869        -0.00110          5.12869         -0.00110          5.12869         -0.00110          5.12869         -0.00110        -3.37908         2.83086        -3.37908         2.83086                    22.0            ftp72
1085   4.791667 -0.102216         4.01480         0.00424          4.01480          0.00424          4.01480          0.00424          4.01480          0.00424        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1086   4.689451 -0.121533         4.01542         0.00412          4.01542          0.00412          4.01542          0.00412          4.01542          0.00412        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1087   4.567918 -0.106112         4.01592         0.00402          4.01592          0.00402          4.01592          0.00402          4.01592          0.00402        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1088   4.461806 -0.017361         4.01633         0.00400          4.01633          0.00400          4.01633          0.00400          4.01633          0.00400        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1089   4.444444  0.034722         4.01673         0.00403          4.01673          0.00403          4.01673          0.00403          4.01673          0.00403        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1090   4.479167 -0.067536         4.01715         0.00396          4.01715          0.00396          4.01715          0.00396          4.01715          0.00396        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1091   4.411630 -0.260418         4.01751         0.00372          4.01751          0.00372          4.01751          0.00372          4.01751          0.00372        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1092   4.151212 -0.154479         4.01763         0.00358          4.01763          0.00358          4.01763          0.00358          4.01763          0.00358        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1093   3.996733 -0.125206         4.01762         0.00346          4.01762          0.00346          4.01762          0.00346          4.01762          0.00346        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1094   3.871528 -1.105953         4.01748         0.00245          4.01748          0.00245          4.01748          0.00245          4.01748          0.00245        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1095   2.765575 -1.376876         4.01634         0.00119          4.01634          0.00119          4.01634          0.00119          4.01634          0.00119        -3.96070         2.83086        -3.96070         2.83086                     9.0     wltp_class3b
1096   1.388699 -1.331230         4.01394        -0.00003          4.01394         -0.00003          4.01394         -0.00003          4.01394         -0.00003        -3.96070         2.83086        -3.96070         2.83086                     9.0     wltp_class3b
1097   0.057469 -0.057469         4.01034        -0.00008          4.01034         -0.00008          4.01034         -0.00008          4.01034         -0.00008        -3.96070         2.83086        -3.96070         2.83086                     9.0            ftp72
1098   0.000000  0.000000         4.00669        -0.00008          4.00669         -0.00008          4.00669         -0.00008          4.00669         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    10.0            ftp72
1099   0.000000  0.000000         4.00305        -0.00008          4.00305         -0.00008          4.00305         -0.00008          4.00305         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    11.0            ftp72
1100   0.000000  0.000000         3.99941        -0.00008          3.99941         -0.00008          3.99941         -0.00008          3.99941         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    12.0            ftp72
1101   0.000000  0.000000         3.99578        -0.00008          3.99578         -0.00008          3.99578         -0.00008          3.99578         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    13.0            ftp72
1102   0.000000  0.000000         3.99216        -0.00008          3.99216         -0.00008          3.99216         -0.00008          3.99216         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    14.0            ftp72
1103   0.000000  0.000000         3.98855        -0.00008          3.98855         -0.00008          3.98855         -0.00008          3.98855         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    15.0            ftp72
1104   0.000000  0.000000         3.98494        -0.00008          3.98494         -0.00008          3.98494         -0.00008          3.98494         -0.00008        -3.96070         2.83086        -3.96070         2.83086                    16.0            ftp72